import type { Metadata } from "next";
import "../styles/index.css";
import "../styles/app.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <LoaderContainer align='flex-start'>
          <div className="absolute flex items-center justify-center top-0 left-0 bg-gray-100/10 h-[100vh] w-[100vw] z-999">
            <div className="spinner"></div>
          </div>
        </LoaderContainer> */}
        {children}
      </body>
    </html>
  );
}
